# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: abd9a678fd17b5dfcab8706080b6a9fa6fdbce6c82f2cbbe57281d9802ccb5688953e40cbb65453b7dcc4d21e5e4b3d21964091397738e8cc61792836448e297


test:
  secret_key_base: a52c47d97231bb7f000789f26fb3657c30e76f11ed19750c3d2ec52039bc800cd73debb846f73bc6baf85bea9a6da07cbfe2e86dfb2106bfb11c40547ed16a06

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
